### ISSUE TITLE
Build fails with error: could not create 'build': File exists

### ISSUE THREAD

**Issue by itssimon** [pachyderm/python-pachyderm#20] opened 2018-05-07 06:42 UTC
OS: macOS High Sierra
Python 3.6.4 (Anaconda)

Trying to build from source:

```
~/Repos/python-pachyderm $ python setup.py install
/usr/local/anaconda3/lib/python3.6/site-packages/setuptools/dist.py:355: UserWarning: Normalizing '1.6.8-9' to '1.6.8.post9'
  normalized_version,
running install
running bdist_egg
running egg_info
writing src/python_pachyderm.egg-info/PKG-INFO
writing dependency_links to src/python_pachyderm.egg-info/dependency_links.txt
writing requirements to src/python_pachyderm.egg-info/requires.txt
writing top-level names to src/python_pachyderm.egg-info/top_level.txt
reading manifest file 'src/python_pachyderm.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.dylib' found anywhere in distribution
writing manifest file 'src/python_pachyderm.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
creating build
error: could not create 'build': File exists
```

Trying to install via pip:

```
~ $ pip install python-pachyderm
Collecting python-pachyderm
  Using cached https://files.pythonhosted.org/packages/09/11/8e362821d7a752e45753e58ecf700b8f4ca84d740f8aa64a053ddef8b24c/python-pachyderm-1.6.8.post9.tar.gz
Requirement already satisfied: protobuf in /usr/local/anaconda3/lib/python3.6/site-packages (from python-pachyderm) (3.5.2.post1)
Requirement already satisfied: grpcio in /usr/local/anaconda3/lib/python3.6/site-packages (from python-pachyderm) (1.11.0)
Requirement already satisfied: future>=0.14 in /usr/local/anaconda3/lib/python3.6/site-packages (from python-pachyderm) (0.16.0)
Requirement already satisfied: setuptools in /usr/local/anaconda3/lib/python3.6/site-packages (from protobuf->python-pachyderm) (38.4.0)
Requirement already satisfied: six>=1.9 in /usr/local/anaconda3/lib/python3.6/site-packages (from protobuf->python-pachyderm) (1.11.0)
Building wheels for collected packages: python-pachyderm
  Running setup.py bdist_wheel for python-pachyderm ... error
  Complete output from command /usr/local/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/gn/nbkfw4214tq4bfhjpcsr5wrr0000gn/T/pip-install-bwc3fnkb/python-pachyderm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/gn/nbkfw4214tq4bfhjpcsr5wrr0000gn/T/pip-wheel-7oe8a4bu --python-tag cp36:
  /usr/local/anaconda3/lib/python3.6/site-packages/setuptools/dist.py:355: UserWarning: Normalizing '1.6.8-9' to '1.6.8.post9'
    normalized_version,
  running bdist_wheel
  running build
  running build_py
  creating build
  error: could not create 'build': File exists
  
  ----------------------------------------
  Failed building wheel for python-pachyderm
  Running setup.py clean for python-pachyderm
Failed to build python-pachyderm
awscli 1.14.68 has requirement botocore==1.9.21, but you'll have botocore 1.9.22 which is incompatible.
Installing collected packages: python-pachyderm
  Running setup.py install for python-pachyderm ... error
    Complete output from command /usr/local/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/gn/nbkfw4214tq4bfhjpcsr5wrr0000gn/T/pip-install-bwc3fnkb/python-pachyderm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/gn/nbkfw4214tq4bfhjpcsr5wrr0000gn/T/pip-record-3uk4hqtv/install-record.txt --single-version-externally-managed --compile:
    /usr/local/anaconda3/lib/python3.6/site-packages/setuptools/dist.py:355: UserWarning: Normalizing '1.6.8-9' to '1.6.8.post9'
      normalized_version,
    running install
    running build
    running build_py
    creating build
    error: could not create 'build': File exists
    
    ----------------------------------------
Command "/usr/local/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/gn/nbkfw4214tq4bfhjpcsr5wrr0000gn/T/pip-install-bwc3fnkb/python-pachyderm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/gn/nbkfw4214tq4bfhjpcsr5wrr0000gn/T/pip-record-3uk4hqtv/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/gn/nbkfw4214tq4bfhjpcsr5wrr0000gn/T/pip-install-bwc3fnkb/python-pachyderm/
```

**Comment by dualphase90** [comment] 2018-06-01 17:01
I have the same issue. Did you figure out a solution for this?

**Comment by suneeta-mall** [comment] 2018-07-08 23:29
Thanks @itssimon .. ^^

**Comment by ysimonson** [comment] 2019-03-06 20:21
Is anyone still seeing this? I can't seem to reproduce it with a case-insensitive APFS volume. The latest changes may have happened to fix it, or changes from setuptools between when this issue was filed and today.

**Comment by itssimon** [comment] 2019-03-11 00:37
Installing via `pip install python-pachyderm` still gives the same error. Installing directly from GitHub via `pip install git+https://github.com/pachyderm/python-pachyderm.git` does work though.

In order to close this issue I propose publishing a new version to PyPI.

**Comment by ysimonson** [comment] 2019-03-11 01:29
Great! Agreed, I'll close this out once a new version is published. That's a WIP because we need to transfer ownership.

**Comment by ysimonson** [comment] 2019-03-20 22:25
Latest version is up: https://pypi.org/project/python-pachyderm/1.8.5.post1/

**Closed by ysimonson** 2019-03-20 22:25 UTC
